# Generated by Django 4.0.3 on 2022-04-10 16:44

import cassa_massa.web.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cell_phone_number',
            field=models.IntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), cassa_massa.web.validators.validate_only_letters]),
        ),
    ]
