# Generated by Django 4.0.3 on 2022-04-12 16:08

import cassa_massa.web.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_contact_cell_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cell_phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=25, validators=[cassa_massa.web.validators.validate_only_letters_and_spaces]),
        ),
    ]
