# Generated by Django 4.0.3 on 2022-04-17 16:54

import cassa_massa.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_services_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_image', models.ImageField(upload_to='')),
                ('table_name', models.CharField(max_length=40, validators=[cassa_massa.web.validators.validate_only_letters_and_spaces])),
                ('table_sizes', models.CharField(max_length=30)),
                ('table_price', models.IntegerField()),
            ],
        ),
    ]
