# Generated by Django 4.0.3 on 2022-04-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_finishedproduct_finishedproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['description']},
        ),
        migrations.AddField(
            model_name='services',
            name='service_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
