# Generated by Django 4.0.3 on 2022-04-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_services_options_services_service_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': (['description'], ['service_order'])},
        ),
    ]
