# Generated by Django 4.0.3 on 2022-04-19 12:51

import cassa_massa.web.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_services_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.CharField(choices=[('Трапезна маса', 'Трапезна маса'), ('Кафе маса', 'Кафе маса'), ('Крайна маса', 'Крайна маса')], max_length=13)),
                ('number_of_seats', models.IntegerField()),
                ('table_shape', models.CharField(choices=[('Кръгла', 'Кръгла'), ('Квадратна', 'Квадратна'), ('Правоъгълна', 'Правоъгълна')], max_length=11)),
                ('table_arrangement', models.CharField(choices=[('River', 'River'), ('Double River', 'Double River'), ('Epoxy Edge', 'Epoxy Edge')], max_length=12)),
                ('wood_type', models.CharField(choices=[('Европейски Орех', 'Европейски Орех'), ('Американски Орех', 'Американски Орех'), ('Дъб', 'Дъб'), ('Череша', 'Череша'), ('Маслина', 'Маслина'), ('Друга екзотична дървесина', 'Друга екзотична дървесина')], max_length=25)),
                ('table_epoxy_color', models.CharField(choices=[('Светльо синьо', 'Светльо синьо'), ('Бяла перла', 'Бяла перла'), ('Зелено', 'Зелено'), ('Златно', 'Златно'), ('Тъмно синьо', 'Тъмно синьо'), ('Плътно черно', 'Плътно черно'), ('Червено', 'Червено'), ('Сиво', 'Сиво'), ('Лилаво', 'Лилаво'), ('Безцветна', 'Безцветна')], max_length=13)),
                ('table_legs', models.CharField(choices=[('Метални крака', 'Метални крака'), ('Дървени крака', 'Дървени крака')], max_length=13)),
                ('table_top_oil', models.CharField(choices=[('Масло сатен', 'Масло сатен'), ('Масло гланц', 'Масло гланц'), ('Масло мат', 'Масло мат')], max_length=11)),
                ('customer_name', models.CharField(max_length=25, validators=[cassa_massa.web.validators.validate_only_letters_and_spaces])),
                ('email', models.EmailField(max_length=254)),
                ('cell_phone_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['service_order', 'description']},
        ),
    ]
