# Generated by Django 4.0.3 on 2022-04-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_rename_title_category_category_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='category_image',
            new_name='images',
        ),
    ]
