# Generated by Django 4.0.3 on 2022-04-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_rename_category_image_images_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='category_image',
        ),
    ]
