# Generated by Django 4.0.3 on 2022-04-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=' '),
            preserve_default=False,
        ),
    ]
