# Generated by Django 4.0.3 on 2022-04-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_alter_images_category_image_photoalbum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoAlbum',
        ),
    ]
