# Generated by Django 4.0.3 on 2022-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_delete_photoalbum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
