# Generated by Django 4.0.3 on 2022-04-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_kategorianeshtosi_kategorianeshtosiimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorianeshtosiimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='KategoriaNeshtoSi',
        ),
        migrations.DeleteModel(
            name='KategoriaNeshtoSiImage',
        ),
    ]
