# Generated by Django 4.0.3 on 2022-04-28 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_images_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoalbum',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_images', to='web.images'),
        ),
    ]
